runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: webapp.app
    secure: always

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest
