runtime: python27
api_version: 1
threadsafe: false

handlers:
  # - url: /level2
  #   static_files: level2-index.html
  #   upload: level2-index.html
  #   secure: always

  # - url: /css
  #   static_dir: css
  #   secure: always

  # - url: /js
  #   static_dir: js
  #   secure: always

  # - url: /css
  #   static_dir: static/css
  #   secure: always

  # - url: /js
  #   static_dir: static/js
  #   secure: always

  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: webapp.app
    secure: always
